app.environment=prod

server.port=${SERVER_PORT:8081}

spring.datasource.url=${PROD_DATASOURCE_URL:jdbc:h2:file:./data/prod/api-service}
spring.datasource.username=${PROD_DATASOURCE_USERNAME:sa}
spring.datasource.password=${PROD_DATASOURCE_PASSWORD:}

management.metrics.tags.environment=prod
