app.environment=staging

server.port=${SERVER_PORT:8082}

spring.datasource.url=${STAGING_DATASOURCE_URL:jdbc:h2:file:./data/staging/api-service}
spring.datasource.username=${STAGING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${STAGING_DATASOURCE_PASSWORD:}

management.metrics.tags.environment=staging
